#cloud-config
users:
  - name: sf-diploma-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBut7pkmBr5pWgoSB1aUcEdDo9XoYPQmolKgv1M+M10V Timofei@Ermolaev.tech