#cloud-config
ssh_pwauth: false

users:
- name: t_ermolaev
  gecos: Operator User
  groups: users,admin,wheel
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  lock_passwd: true
  ssh_authorized_keys:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBut7pkmBr5pWgoSB1aUcEdDo9XoYPQmolKgv1M+M10V Timofei@Ermolaev.tech"