#cloud-config
ssh_pwauth: false

users:
- name: ansible
  gecos: Ansible User
  groups: users,admin,wheel
  sudo: ALL=(ALL) NOPASSWD:ALL
  shell: /bin/bash
  lock_passwd: true
  ssh_authorized_keys:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFH9hqGFs/1hINzaUon0rTqeDjvYfwqOSIklDxQzELYK devops_diploma@skillfactory.ru"
  no_ssh_fingerprints: true